import { Link } from "react-router-dom";
import { Badge } from "../design/Badge";
import { Button } from "../design/Button";
import { Card } from "../design/Card";

const pipelineStages = [
  { title: "Publisher", body: "Internal service calls POST /events with an Idempotency-Key." },
  { title: "Events", body: "One row, status pending_expansion. 202 returned immediately — O(1) regardless of subscriber count." },
  { title: "Expansion loop", body: "Per-tenant advisory lock. One delivery row per subscribed endpoint, atomically." },
  { title: "Endpoint queues", body: "Strict FIFO per endpoint. A worker claims the oldest pending delivery, signs, sends, retries." },
];

const guarantees = [
  { title: "Ordered", body: "One delivery in flight per endpoint at a time. A blocked delivery reports it, and why." },
  { title: "Retried", body: "Full-jitter exponential backoff, six attempts, then the endpoint halts — not silently dropped." },
  { title: "Explainable", body: "Every delivery's exact request and response history, on one screen, no engineer required." },
  { title: "Replayable", body: "Re-deliver any past window without disturbing other endpoints' live traffic." },
];

// Real numbers from evidence/{load,chaos}/*.json and evidence/go/{load,chaos}/*.json
// (checked into the repo, regenerated by `make properties`/`make chaos`/`make load` —
// not live-fetched, so this can drift if those are rerun without updating these
// literals; kept small and named so that gap stays visible rather than hidden).
// The mockup's own numbers here ("0 of 50,000", "1,200 crashes", "under 180ms") were
// placeholder marketing figures with no real evidence behind them — replaced with
// what actually ran.
const results = [
  {
    kicker: "Nothing lost",
    value: "3 of 3 properties hold",
    body: "Expansion order, repeated-key idempotency, and replay crash-safety — each re-run with a fresh random seed on every run, on both backends.",
    command: "make properties",
  },
  {
    kicker: "Nothing stranded",
    value: "5 of 5 chaos scenarios pass",
    body: "Workers crashed or stalled mid-delivery, a partition head blocked then drained — every scenario still resolved to exactly one outcome.",
    command: "make chaos",
  },
  {
    kicker: "Nobody starved",
    value: "p99 226ms (Node) / 127ms (Go)",
    body: "One tenant floods 20 endpoints at once; a quiet tenant's own deliveries stay fast. The spec sets no fixed bound — we hold ourselves to p99 under 5s.",
    command: "make load",
  },
];

// Illustrative only — see the comment at its usage site below.
const exampleAttempts = [
  { attempt: 1, time: "14:02:11", status: 503, note: "upstream busy", opacity: 0.6 },
  { attempt: 2, time: "14:02:13", status: 504, note: "gateway timeout", opacity: 0.75 },
  { attempt: 3, time: "14:02:19", status: 200, note: "delivered in 84 ms", opacity: 1 },
];

const LATEST_RUN_DATE = "2026-08-07";
const LATEST_RUN_COMMIT = "bdd4537";

export function Landing() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--color-bg)" }}>
      <header
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          borderBottom: "1px solid var(--color-divider)",
          padding: "0 24px",
          height: 64,
        }}
      >
        <span
          style={{
            fontFamily: "var(--font-heading)",
            fontWeight: 700,
            fontSize: 20,
            letterSpacing: "0.04em",
            textTransform: "uppercase",
          }}
        >
          Gauntlet Relay
        </span>
        <nav style={{ display: "flex", alignItems: "center", gap: 24 }}>
          <a href="#pipeline" style={{ color: "var(--color-text)", fontSize: 14 }}>
            The pipeline
          </a>
          <a href="#results" style={{ color: "var(--color-text)", fontSize: 14 }}>
            Results
          </a>
          <a href="#guarantees" style={{ color: "var(--color-text)", fontSize: 14 }}>
            Guarantees
          </a>
          <Link to="/console/overview">
            <Button variant="primary">Open the dashboard</Button>
          </Link>
        </nav>
      </header>

      <section style={{ display: "flex", gap: 48, padding: "64px 24px", maxWidth: 1100, margin: "0 auto" }}>
        <div style={{ flex: 1 }}>
          <h1
            style={{
              fontFamily: "var(--font-heading)",
              fontWeight: 600,
              fontSize: "clamp(36px, 5vw, 64px)",
              lineHeight: 1.05,
              letterSpacing: "0.01em",
              textTransform: "uppercase",
              marginBottom: 20,
            }}
          >
            Every webhook accounted for.
            <br />
            <span style={{ color: "var(--color-accent)" }}>Out loud.</span>
          </h1>
          <p style={{ maxWidth: 420, marginBottom: 24, color: "var(--color-text-muted)" }}>
            Gauntlet Relay delivers your events in the order you published them, keeps retrying the ones that fail, and
            shows your team exactly what happened to any single event — on one screen, no engineer required.
          </p>
          <div style={{ display: "flex", gap: 12 }}>
            <Link to="/console/overview">
              <Button variant="primary">Open the dashboard</Button>
            </Link>
            <a href="https://gitlab.com" target="_blank" rel="noreferrer">
              <Button variant="secondary">Source code</Button>
            </a>
          </div>
        </div>
      </section>

      <section id="pipeline" style={{ padding: "48px 24px", maxWidth: 1100, margin: "0 auto" }}>
        <h2 style={{ fontSize: 22, marginBottom: 24 }}>The pipeline</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16 }}>
          {pipelineStages.map((stage, i) => (
            <Card key={stage.title} cornerMarks style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--color-text-muted)" }}>
                {String(i + 1).padStart(2, "0")}
              </span>
              <h3 style={{ fontSize: 15 }}>{stage.title}</h3>
              <p style={{ fontSize: 13, color: "var(--color-text-muted)", margin: 0 }}>{stage.body}</p>
            </Card>
          ))}
        </div>
      </section>

      <section id="results" style={{ padding: "8px 24px 48px", maxWidth: 1100, margin: "0 auto" }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 14, flexWrap: "wrap", marginBottom: 14 }}>
          <span
            style={{
              fontSize: 13,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              fontWeight: 600,
              color: "var(--color-accent-700)",
            }}
          >
            Latest run
          </span>
          <span style={{ fontSize: 13, color: "var(--color-text-muted)" }}>
            {LATEST_RUN_DATE} · commit <code style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}>{LATEST_RUN_COMMIT}</code> ·
            checked in under evidence/, not live-fetched
          </span>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 }}>
          {results.map((r) => (
            <Card key={r.kicker} cornerMarks style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              <span style={{ fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-text-muted)" }}>
                {r.kicker}
              </span>
              <span
                style={{
                  fontFamily: "var(--font-heading)",
                  fontSize: "clamp(22px, 2.2vw, 28px)",
                  lineHeight: 1.05,
                  letterSpacing: "0.01em",
                  textTransform: "uppercase",
                  color: "var(--color-accent-800)",
                }}
              >
                {r.value}
              </span>
              <p style={{ fontSize: 13, lineHeight: "20px", margin: "2px 0 0", color: "var(--color-text-muted)" }}>{r.body}</p>
              <code style={{ marginTop: "auto", paddingTop: 10, fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--color-accent-700)" }}>
                {r.command}
              </code>
            </Card>
          ))}
        </div>
      </section>

      <section id="guarantees" style={{ padding: "24px 24px 64px", maxWidth: 1100, margin: "0 auto" }}>
        <h2 style={{ fontSize: 22, marginBottom: 24 }}>Guarantees</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16 }}>
          {guarantees.map((g) => (
            <Card key={g.title}>
              <h3 style={{ fontSize: 15, marginBottom: 6 }}>{g.title}</h3>
              <p style={{ fontSize: 13, color: "var(--color-text-muted)", margin: 0 }}>{g.body}</p>
            </Card>
          ))}
        </div>
        <p style={{ fontSize: 13, color: "var(--color-text-muted)", marginTop: 16 }}>
          Every guarantee above has a test behind it that runs on every change — see "Results" above, not a claim made by
          eye.
        </p>
      </section>

      <section style={{ padding: "24px 24px 56px", maxWidth: 1100, margin: "0 auto" }}>
        <Card cornerMarks style={{ display: "flex", flexWrap: "wrap", gap: 32, alignItems: "center", padding: "26px 30px" }}>
          <div style={{ flex: "1 1 300px" }}>
            <h2 style={{ fontFamily: "var(--font-heading)", fontSize: 24, letterSpacing: "0.02em", textTransform: "uppercase", margin: 0 }}>
              One screen answers &ldquo;what happened?&rdquo;
            </h2>
            <p style={{ fontSize: 15, lineHeight: "23px", margin: "12px 0 0", maxWidth: "46ch", color: "var(--color-text-muted)" }}>
              Every attempt, every response, every retry — in the order they happened. If someone on your team cannot
              close a ticket from it, we have not finished.
            </p>
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 20 }}>
              <Link to="/console/overview">
                <Button variant="primary">Open the dashboard</Button>
              </Link>
              <a href="https://gitlab.com" target="_blank" rel="noreferrer">
                <Button variant="secondary">Source code</Button>
              </a>
            </div>
          </div>
          <div style={{ flex: "1 1 340px", minWidth: 300 }}>
            {/* Illustrative example, not a live query — the real, live version of
               this exact view is the actual Delivery Detail screen the "Open the
               dashboard" link goes to. */}
            <div
              style={{
                display: "flex",
                alignItems: "baseline",
                gap: 10,
                paddingBottom: 8,
                borderBottom: "1px solid var(--color-text)",
              }}
            >
              <span style={{ fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-text-muted)" }}>
                Delivery (example)
              </span>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--color-accent-700)" }}>dlv_8f21c4a0</span>
              <span style={{ marginLeft: "auto" }}>
                <Badge tone="accent">Succeeded</Badge>
              </span>
            </div>
            {exampleAttempts.map((a) => (
              <div
                key={a.attempt}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 12,
                  padding: "8px 0",
                  borderBottom: "1px solid var(--color-divider)",
                  opacity: a.opacity,
                }}
              >
                <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--color-text-muted)", width: 58, flex: "none" }}>
                  {a.time}
                </span>
                <span style={{ fontSize: 12, letterSpacing: "0.06em", textTransform: "uppercase", width: 62, flex: "none" }}>
                  Try {a.attempt}
                </span>
                <Badge tone={a.status === 200 ? "accent" : "neutral"}>{a.status}</Badge>
                <span style={{ fontSize: 12, color: "var(--color-text-muted)", marginLeft: "auto", whiteSpace: "nowrap" }}>
                  {a.note}
                </span>
              </div>
            ))}
          </div>
        </Card>
      </section>

      <footer
        style={{
          maxWidth: 1100,
          margin: "0 auto",
          padding: "24px 24px 48px",
          borderTop: "1px solid var(--color-divider)",
          fontSize: 13,
          color: "var(--color-text-muted)",
        }}
      >
        Gauntlet Relay v0.2.0 — Node/TypeScript and Go implementations, one schema, one REST contract.
      </footer>
    </div>
  );
}
