import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Badge } from "../design/Badge";
import { Button } from "../design/Button";
import { Card } from "../design/Card";

const guarantees = [
  { title: "Ordered", body: "One delivery in flight per endpoint at a time. A blocked delivery reports it, and why." },
  { title: "Retried", body: "Full-jitter exponential backoff, six attempts, then the endpoint halts — not silently dropped." },
  { title: "Explainable", body: "Every delivery's exact request and response history, on one screen, no engineer required." },
  { title: "Replayable", body: "Re-deliver any past window without disturbing other endpoints' live traffic." },
];

// Real numbers from evidence/{load,chaos}/*.json and evidence/go/{load,chaos}/*.json
// (checked into the repo, regenerated by `make properties`/`make chaos`/`make load` —
// not live-fetched, so this can drift if those are rerun without updating these
// literals; kept small and named so that gap stays visible rather than hidden).
// The mockup's own numbers here ("0 of 50,000", "1,200 crashes", "under 180ms") were
// placeholder marketing figures with no real evidence behind them — replaced with
// what actually ran.
const results = [
  {
    kicker: "Nothing lost",
    value: "3 of 3 properties hold",
    body: "Expansion order, repeated-key idempotency, and replay crash-safety — each re-run with a fresh random seed on every run, on both backends.",
    command: "make properties",
  },
  {
    kicker: "Nothing stranded",
    value: "5 of 5 chaos scenarios pass",
    body: "Workers crashed or stalled mid-delivery, a partition head blocked then drained — every scenario still resolved to exactly one outcome.",
    command: "make chaos",
  },
  {
    kicker: "Nobody starved",
    value: "p99 226ms (Node) / 127ms (Go)",
    body: "One tenant floods 20 endpoints at once; a quiet tenant's own deliveries stay fast. The spec sets no fixed bound — we hold ourselves to p99 under 5s.",
    command: "make load",
  },
];

// Illustrative only — see the comment at its usage site below.
const exampleAttempts = [
  { attempt: 1, time: "14:02:11", status: 503, note: "upstream busy", opacity: 0.6 },
  { attempt: 2, time: "14:02:13", status: 504, note: "gateway timeout", opacity: 0.75 },
  { attempt: 3, time: "14:02:19", status: 200, note: "delivered in 84 ms", opacity: 1 },
];

const LATEST_RUN_DATE = "2026-08-07";
const LATEST_RUN_COMMIT = "bdd4537";

// --- The pipeline diagram --------------------------------------------------
// Boxes and their positions mirror the reference mockup's own layout
// (Publisher → API process → Postgres [events/deliveries] → Expansion/Delivery
// loops → 3 receiver endpoints). What's real: the box labels and mechanism
// text (advisory lock, FOR UPDATE SKIP LOCKED, one-worker-per-endpoint-at-a-
// time), the runtime toggle (matches the real Node/Go backend switcher this
// app already has, ADR-008), the scenario names (drawn from the actual named
// tests in node/load, node/chaos, go/load, go/chaos), the worker count (3,
// matches WORKER_COUNT in every load/chaos harness), and the "Publish p99"
// stat (real numbers from evidence/load/publish-latency-flat.json and
// evidence/go/load/publish-latency-flat.json, keyed by band → event level).
// What's illustrative: Published/Queue depth/In flight/Delivered are a
// client-side simulation, and the moving dot's timing is compressed — there
// is no live backend behind a marketing page. Said outright below the panel,
// same as the mockup's own disclaimer for this exact section.

type Runtime = "Node" | "Go";
type Band = "Quiet" | "Moderate" | "Flood";

const RUNTIMES: Runtime[] = ["Node", "Go"];
const BANDS: Band[] = ["Quiet", "Moderate", "Flood"];

// evidence/load/publish-latency-flat.json + evidence/go/load/publish-latency-flat.json,
// resultsByLevel[10|1000|10000].p99 — Quiet/Moderate/Flood map to the 10/1000/10000
// concurrent-publish levels those files measured at.
const PUBLISH_P99_MS: Record<Runtime, Record<Band, number>> = {
  Node: { Quiet: 37.3, Moderate: 7.7, Flood: 2.6 },
  Go: { Quiet: 27.7, Moderate: 1.6, Flood: 3.2 },
};

const WORKER_COUNT = 3;

const SCENARIOS = [
  { label: "Steady state", note: "Events publish and expand continuously; nothing is failing." },
  {
    label: "Noisy neighbor",
    note: "One tenant floods 20 endpoints at once; a quiet tenant's own deliveries stay fast (real result: p99 226ms Node / 127ms Go — see Results below).",
  },
  { label: "Worker crash", note: "A worker is killed mid-delivery. Another worker resumes the claim — the event still reaches exactly one outcome." },
  { label: "Partition drains", note: "The head of an endpoint's queue is blocked on a stuck delivery; it clears, then the rest of the queue drains in order." },
  { label: "Tarpit fairness", note: "A slow-to-respond receiver holds only its own queue back — other endpoints keep moving." },
  { label: "Replay", note: "A past time window is re-delivered by inserting new rows into the same per-endpoint queue as live traffic." },
] as const;

interface Box {
  left: number;
  top: number;
  width: number;
  height: number;
}

const PIPELINE_NODES: (Box & { id: string; label: string; sub: string })[] = [
  { id: "publisher", label: "Publisher", sub: "internal service", left: 0, top: 42.55, width: 9.52, height: 17.87 },
  { id: "api", label: "API process", sub: "POST /events → 202", left: 13.39, top: 42.55, width: 12.26, height: 17.87 },
  { id: "events", label: "events", sub: "status = pending_expansion", left: 31.61, top: 15.74, width: 20.97, height: 19.57 },
  { id: "expansion", label: "Expansion loop", sub: "advisory lock / tenant", left: 58.55, top: 15.74, width: 13.87, height: 19.57 },
  { id: "deliveries", label: "deliveries", sub: "one row per (event, endpoint)", left: 31.61, top: 64.26, width: 20.97, height: 19.57 },
  {
    id: "delivery-loop",
    label: "Delivery loop",
    sub: `${WORKER_COUNT} workers, FOR UPDATE SKIP LOCKED`,
    left: 58.55,
    top: 64.26,
    width: 13.87,
    height: 19.57,
  },
];

const RECEIVER_LEFT = 76.29;
const RECEIVER_WIDTH = 23.71;
const RECEIVER_HEIGHT = 24.68;
const RECEIVERS = [
  { name: "Billing service", url: "https://billing.example.com/hooks", top: 5.96 },
  { name: "Inventory sync", url: "https://inventory.example.com/hooks", top: 37.45 },
  { name: "Analytics pipe", url: "https://analytics.example.com/hooks", top: 68.94 },
];

// Sequential PIPELINE_NODES indices the dot walks through, in order. The
// last leg (Delivery loop → a receiver) is drawn separately below, once per
// receiver, since which receiver is "this leg's" target changes every lap.
const PIPELINE_EDGES: [number, number][] = [
  [0, 1],
  [1, 2],
  [2, 3],
  [3, 4],
  [4, 5],
];

const TICK_MS = 900;
// How often the traveling dot's position is recomputed while it's in transit
// between two boxes — smaller than TICK_MS so the motion reads as a
// continuous glide rather than a jump, without needing a CSS transition
// (which was the previous approach's problem: a position transition and the
// box border's color change are two independently-timed animations driven by
// the same state change, so they could visibly disagree mid-flight — see the
// prior fix's commit message). Here there's a single continuous `progress`
// value and everything else — the dot's position, which box is "active" and
// therefore highlighted, which receiver a lap is headed toward — is derived
// from it in the same render, every render, so nothing can drift apart.
const FRAME_MS = 60;
const TOTAL_STAGES = PIPELINE_NODES.length + 1; // +1 for "at a receiver"
const BAND_MULTIPLIER: Record<Band, number> = { Quiet: 1, Moderate: 3, Flood: 9 };

function boxCenter(box: Box): { x: number; y: number } {
  return { x: box.left + box.width / 2, y: box.top + box.height / 2 };
}

function receiverCenter(receiverIndex: number): { x: number; y: number } {
  const r = RECEIVERS[receiverIndex]!;
  return boxCenter({ left: RECEIVER_LEFT, top: r.top, width: RECEIVER_WIDTH, height: RECEIVER_HEIGHT });
}

// index 0..5 = PIPELINE_NODES, index 6 = "at a receiver" (whichever one this
// lap is headed to/dwelling at).
function centerForIndex(index: number, receiverIndex: number): { x: number; y: number } {
  return index < PIPELINE_NODES.length ? boxCenter(PIPELINE_NODES[index]!) : receiverCenter(receiverIndex);
}

function lerp(a: { x: number; y: number }, b: { x: number; y: number }, t: number): { x: number; y: number } {
  return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
}

function SegGroup<T extends string>({
  label,
  options,
  value,
  onChange,
  wrap,
}: {
  label: string;
  options: readonly T[];
  value: T;
  onChange: (v: T) => void;
  wrap?: boolean;
}) {
  return (
    <div>
      <div style={{ fontSize: 11, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-text-muted)", marginBottom: 7 }}>
        {label}
      </div>
      <div style={{ display: "flex", gap: 6, flexWrap: wrap ? "wrap" : "nowrap" }}>
        {options.map((opt) => (
          <button
            key={opt}
            type="button"
            onClick={() => onChange(opt)}
            style={{
              fontFamily: "var(--font-body)",
              fontSize: 12,
              padding: "6px 10px",
              borderRadius: "var(--radius)",
              border: "1px solid var(--color-divider)",
              cursor: "pointer",
              background: opt === value ? "var(--color-accent)" : "transparent",
              color: opt === value ? "var(--color-bg)" : "var(--color-text)",
              whiteSpace: "nowrap",
            }}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div style={{ background: "var(--color-bg)", padding: "11px 12px" }}>
      <div style={{ fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-text-muted)" }}>{label}</div>
      <div style={{ fontFamily: "var(--font-heading)", fontSize: 24, lineHeight: "28px" }}>{value}</div>
    </div>
  );
}

function PipelineDiagram() {
  const [runtime, setRuntime] = useState<Runtime>("Node");
  const [band, setBand] = useState<Band>("Moderate");
  const [scenarioIndex, setScenarioIndex] = useState(0);
  const [playing, setPlaying] = useState(true);
  // Continuous, in stage-units — grows without bound rather than wrapping, so
  // "which lap" (and therefore which receiver this lap targets) is a plain
  // derived value instead of its own piece of state to keep in sync.
  const [progress, setProgress] = useState(0);
  const [published, setPublished] = useState(0);
  const [delivered, setDelivered] = useState(0);
  const tickCount = useRef(0);

  const bandMultiplier = BAND_MULTIPLIER[band];

  useEffect(() => {
    if (!playing) return;
    const id = setInterval(() => setProgress((p) => p + FRAME_MS / TICK_MS), FRAME_MS);
    return () => clearInterval(id);
  }, [playing]);

  const stageIndex = Math.floor(progress) % TOTAL_STAGES;
  const lap = Math.floor(progress / TOTAL_STAGES);
  const receiverIndex = lap % RECEIVERS.length;
  // Only the approach into a receiver (edge 5→6) is a real animated glide;
  // once there, the dot holds still — advancing straight on to the next
  // stage would mean flying back across the whole diagram to the Publisher,
  // which isn't a real hand-off this system makes.
  const t = stageIndex < PIPELINE_NODES.length ? progress - Math.floor(progress) : 0;

  // Fires once per stage crossing (stageIndex changes roughly once per
  // TICK_MS) — the discrete "tick" the stat counters and dot both used to
  // share before the dot's motion became continuous.
  useEffect(() => {
    tickCount.current += 1;
    setPublished((p) => p + bandMultiplier);
    setDelivered((d) => d + Math.max(0, bandMultiplier - 1));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stageIndex]);

  useEffect(() => {
    setPublished(0);
    setDelivered(0);
    setProgress(0);
  }, [runtime, band, scenarioIndex]);

  const scenario = SCENARIOS[scenarioIndex]!;
  const queueDepth = Math.max(0, Math.round(bandMultiplier * 3 + Math.sin(tickCount.current / 2) * bandMultiplier));
  const inFlight = 1 + (tickCount.current % WORKER_COUNT);
  const publishP99 = PUBLISH_P99_MS[runtime][band];
  const dot =
    stageIndex < PIPELINE_NODES.length
      ? lerp(centerForIndex(stageIndex, receiverIndex), centerForIndex(stageIndex + 1, receiverIndex), t)
      : receiverCenter(receiverIndex);

  return (
    <div>
      <div style={{ display: "flex", flexWrap: "wrap", gap: "20px 32px", alignItems: "flex-end", marginBottom: 22 }}>
        <SegGroup label="Implementation" options={RUNTIMES} value={runtime} onChange={setRuntime} />
        <SegGroup label="Traffic band" options={BANDS} value={band} onChange={setBand} />
        <div style={{ flex: 1, minWidth: 320 }}>
          <SegGroup
            label="Scenario — from the test suite"
            options={SCENARIOS.map((s) => s.label)}
            value={scenario.label}
            onChange={(label) => setScenarioIndex(SCENARIOS.findIndex((s) => s.label === label))}
            wrap
          />
        </div>
        <Button variant="secondary" onClick={() => setPlaying((p) => !p)} style={{ minWidth: 92 }}>
          {playing ? "Pause" : "Play"}
        </Button>
      </div>

      <div style={{ overflowX: "auto", padding: "10px 8px 6px" }}>
        <div style={{ position: "relative", minWidth: 1000, width: "100%", aspectRatio: "1240 / 470" }}>
          <div
            style={{
              position: "absolute",
              left: "29.52%",
              top: "5.96%",
              width: "25.16%",
              height: "88.09%",
              border: "1px dashed var(--color-divider)",
            }}
          />
          <div
            style={{
              position: "absolute",
              left: "29.52%",
              top: "5.96%",
              width: "25.16%",
              transform: "translateY(-100%)",
              paddingBottom: 5,
              fontSize: 11,
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              color: "var(--color-text-muted)",
            }}
          >
            Postgres — the queue
          </div>

          {/* The wire the dot flows along — same percentage coordinate space
             as the boxes below (viewBox 0 0 100 100 + preserveAspectRatio
             "none" maps 1:1 onto left/top percentages), so a line's
             endpoints always meet a box's center exactly. */}
          <svg
            aria-hidden
            viewBox="0 0 100 100"
            preserveAspectRatio="none"
            style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}
          >
            {PIPELINE_EDGES.map(([a, b]) => {
              const pa = boxCenter(PIPELINE_NODES[a]!);
              const pb = boxCenter(PIPELINE_NODES[b]!);
              return (
                <line key={`${a}-${b}`} x1={pa.x} y1={pa.y} x2={pb.x} y2={pb.y} style={{ stroke: "var(--color-divider)" }} strokeWidth={0.3} />
              );
            })}
            {RECEIVERS.map((_, i) => {
              const pa = boxCenter(PIPELINE_NODES[PIPELINE_NODES.length - 1]!);
              const pb = receiverCenter(i);
              return (
                <line
                  key={`delivery-loop-${i}`}
                  x1={pa.x}
                  y1={pa.y}
                  x2={pb.x}
                  y2={pb.y}
                  style={{ stroke: "var(--color-divider)" }}
                  strokeWidth={0.3}
                />
              );
            })}
          </svg>

          {PIPELINE_NODES.map((n, i) => (
            <Card
              key={n.id}
              cornerMarks
              style={{
                position: "absolute",
                left: `${n.left}%`,
                top: `${n.top}%`,
                width: `${n.width}%`,
                height: `${n.height}%`,
                padding: "9px 11px",
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                borderColor: stageIndex === i ? "var(--color-accent)" : "var(--color-divider)",
              }}
            >
              <div style={{ fontFamily: "var(--font-heading)", fontSize: 14, letterSpacing: "0.04em", textTransform: "uppercase", lineHeight: 1.1 }}>
                {n.label}
              </div>
              <div style={{ fontSize: 11, lineHeight: "15px", marginTop: 4, color: "var(--color-text-muted)" }}>{n.sub}</div>
            </Card>
          ))}

          {RECEIVERS.map((r, i) => (
            <Card
              key={r.name}
              cornerMarks
              style={{
                position: "absolute",
                left: `${RECEIVER_LEFT}%`,
                top: `${r.top}%`,
                width: `${RECEIVER_WIDTH}%`,
                height: `${RECEIVER_HEIGHT}%`,
                padding: "9px 11px",
                display: "flex",
                flexDirection: "column",
                gap: 3,
                borderColor: stageIndex === PIPELINE_NODES.length && receiverIndex === i ? "var(--color-accent)" : "var(--color-divider)",
              }}
            >
              <div style={{ fontFamily: "var(--font-heading)", fontSize: 14, letterSpacing: "0.04em", textTransform: "uppercase", lineHeight: 1.1 }}>
                {r.name}
              </div>
              <div style={{ fontSize: 11, lineHeight: "15px", color: "var(--color-text-muted)" }}>{r.url}</div>
              <div style={{ marginTop: "auto" }}>
                <Badge tone={stageIndex === PIPELINE_NODES.length && receiverIndex === i ? "accent" : "neutral"}>
                  {stageIndex === PIPELINE_NODES.length && receiverIndex === i ? "delivering" : "idle"}
                </Badge>
              </div>
            </Card>
          ))}

          {/* The traveling dot — its position is the ONE lerp between
             `centerForIndex(stageIndex, ...)` and `centerForIndex(stageIndex
             + 1, ...)`, the same stageIndex that colors the boxes' borders
             above. There's no independent animation timeline here (no CSS
             transition) — position and border both fall out of the same
             `progress` value on every render, so they can't disagree. */}
          <div
            aria-hidden
            style={{
              position: "absolute",
              left: `${dot.x}%`,
              top: `${dot.y}%`,
              width: 10,
              height: 10,
              marginLeft: -5,
              marginTop: -5,
              borderRadius: "50%",
              background: "var(--color-accent)",
            }}
          />
        </div>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 380px), 1fr))",
          gap: "24px clamp(24px, 5vw, 64px)",
          marginTop: 26,
          alignItems: "start",
        }}
      >
        <Card cornerMarks style={{ padding: "16px 18px" }}>
          <div style={{ fontFamily: "var(--font-heading)", fontSize: 19, letterSpacing: "0.03em", textTransform: "uppercase", lineHeight: 1.15 }}>
            {scenario.label}
          </div>
          <p style={{ fontSize: 14, lineHeight: "21px", margin: "8px 0 0", color: "var(--color-text-muted)", maxWidth: "66ch" }}>
            {scenario.note}
          </p>
        </Card>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
            gap: 1,
            background: "var(--color-divider)",
            border: "1px solid var(--color-divider)",
          }}
        >
          <Stat label="Published" value={published} />
          <Stat label="Publish p99" value={`${publishP99}ms`} />
          <Stat label="Workers" value={WORKER_COUNT} />
          <Stat label="Queue depth" value={queueDepth} />
          <Stat label="In flight" value={inFlight} />
          <Stat label="Delivered" value={delivered} />
        </div>
      </div>
      <p style={{ fontSize: 12, lineHeight: "18px", margin: "14px 0 0", color: "var(--color-text-muted)" }}>
        Time is compressed, and Published/Queue depth/In flight/Delivered are a representative simulation — the pipeline
        stages, the runtime toggle, the worker count, and the publish-time number are the real ones.
      </p>
    </div>
  );
}
// --- end pipeline diagram ---------------------------------------------------

export function Landing() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--color-bg)" }}>
      <header
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          borderBottom: "1px solid var(--color-divider)",
          padding: "0 24px",
          height: 64,
        }}
      >
        <span
          style={{
            fontFamily: "var(--font-heading)",
            fontWeight: 700,
            fontSize: 20,
            letterSpacing: "0.04em",
            textTransform: "uppercase",
          }}
        >
          Gauntlet Relay
        </span>
        <nav style={{ display: "flex", alignItems: "center", gap: 24 }}>
          <a href="#pipeline" style={{ color: "var(--color-text)", fontSize: 14 }}>
            The pipeline
          </a>
          <a href="#results" style={{ color: "var(--color-text)", fontSize: 14 }}>
            Results
          </a>
          <a href="#guarantees" style={{ color: "var(--color-text)", fontSize: 14 }}>
            Guarantees
          </a>
          <Link to="/console/overview">
            <Button variant="primary">Open the dashboard</Button>
          </Link>
        </nav>
      </header>

      <section style={{ display: "flex", gap: 48, padding: "64px 24px", maxWidth: 1100, margin: "0 auto" }}>
        <div style={{ flex: 1 }}>
          <h1
            style={{
              fontFamily: "var(--font-heading)",
              fontWeight: 600,
              fontSize: "clamp(36px, 5vw, 64px)",
              lineHeight: 1.05,
              letterSpacing: "0.01em",
              textTransform: "uppercase",
              marginBottom: 20,
            }}
          >
            Every webhook accounted for.
            <br />
            <span style={{ color: "var(--color-accent)" }}>Out loud.</span>
          </h1>
          <p style={{ maxWidth: 420, marginBottom: 24, color: "var(--color-text-muted)" }}>
            Gauntlet Relay delivers your events in the order you published them, keeps retrying the ones that fail, and
            shows your team exactly what happened to any single event — on one screen, no engineer required.
          </p>
          <div style={{ display: "flex", gap: 12 }}>
            <Link to="/console/overview">
              <Button variant="primary">Open the dashboard</Button>
            </Link>
            <a href="https://gitlab.com" target="_blank" rel="noreferrer">
              <Button variant="secondary">Source code</Button>
            </a>
          </div>
        </div>
      </section>

      <section id="pipeline" style={{ padding: "48px 24px 0", maxWidth: 1100, margin: "0 auto" }}>
        <h2 style={{ fontSize: 22, marginBottom: 8 }}>The pipeline</h2>
        <p style={{ fontSize: 13, color: "var(--color-text-muted)", marginBottom: 24 }}>
          Pick a runtime, a traffic band, and a scenario from the test suite — the diagram below animates that scenario
          moving through the real pipeline.
        </p>
        <PipelineDiagram />
      </section>

      <section id="results" style={{ padding: "8px 24px 48px", maxWidth: 1100, margin: "0 auto" }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 14, flexWrap: "wrap", marginBottom: 14 }}>
          <span
            style={{
              fontSize: 13,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              fontWeight: 600,
              color: "var(--color-accent-700)",
            }}
          >
            Latest run
          </span>
          <span style={{ fontSize: 13, color: "var(--color-text-muted)" }}>
            {LATEST_RUN_DATE} · commit <code style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}>{LATEST_RUN_COMMIT}</code> ·
            checked in under evidence/, not live-fetched
          </span>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 }}>
          {results.map((r) => (
            <Card key={r.kicker} cornerMarks style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              <span style={{ fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-text-muted)" }}>
                {r.kicker}
              </span>
              <span
                style={{
                  fontFamily: "var(--font-heading)",
                  fontSize: "clamp(22px, 2.2vw, 28px)",
                  lineHeight: 1.05,
                  letterSpacing: "0.01em",
                  textTransform: "uppercase",
                  color: "var(--color-accent-800)",
                }}
              >
                {r.value}
              </span>
              <p style={{ fontSize: 13, lineHeight: "20px", margin: "2px 0 0", color: "var(--color-text-muted)" }}>{r.body}</p>
              <code style={{ marginTop: "auto", paddingTop: 10, fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--color-accent-700)" }}>
                {r.command}
              </code>
            </Card>
          ))}
        </div>
      </section>

      <section id="guarantees" style={{ padding: "24px 24px 64px", maxWidth: 1100, margin: "0 auto" }}>
        <h2 style={{ fontSize: 22, marginBottom: 24 }}>Guarantees</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16 }}>
          {guarantees.map((g) => (
            <Card key={g.title}>
              <h3 style={{ fontSize: 15, marginBottom: 6 }}>{g.title}</h3>
              <p style={{ fontSize: 13, color: "var(--color-text-muted)", margin: 0 }}>{g.body}</p>
            </Card>
          ))}
        </div>
        <p style={{ fontSize: 13, color: "var(--color-text-muted)", marginTop: 16 }}>
          Every guarantee above has a test behind it that runs on every change — see "Results" above, not a claim made by
          eye.
        </p>
      </section>

      <section style={{ padding: "24px 24px 56px", maxWidth: 1100, margin: "0 auto" }}>
        <Card cornerMarks style={{ display: "flex", flexWrap: "wrap", gap: 32, alignItems: "center", padding: "26px 30px" }}>
          <div style={{ flex: "1 1 300px" }}>
            <h2 style={{ fontFamily: "var(--font-heading)", fontSize: 24, letterSpacing: "0.02em", textTransform: "uppercase", margin: 0 }}>
              One screen answers &ldquo;what happened?&rdquo;
            </h2>
            <p style={{ fontSize: 15, lineHeight: "23px", margin: "12px 0 0", maxWidth: "46ch", color: "var(--color-text-muted)" }}>
              Every attempt, every response, every retry — in the order they happened. If someone on your team cannot
              close a ticket from it, we have not finished.
            </p>
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 20 }}>
              <Link to="/console/overview">
                <Button variant="primary">Open the dashboard</Button>
              </Link>
              <a href="https://gitlab.com" target="_blank" rel="noreferrer">
                <Button variant="secondary">Source code</Button>
              </a>
            </div>
          </div>
          <div style={{ flex: "1 1 340px", minWidth: 300 }}>
            {/* Illustrative example, not a live query — the real, live version of
               this exact view is the actual Delivery Detail screen the "Open the
               dashboard" link goes to. */}
            <div
              style={{
                display: "flex",
                alignItems: "baseline",
                gap: 10,
                paddingBottom: 8,
                borderBottom: "1px solid var(--color-text)",
              }}
            >
              <span style={{ fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-text-muted)" }}>
                Delivery (example)
              </span>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--color-accent-700)" }}>dlv_8f21c4a0</span>
              <span style={{ marginLeft: "auto" }}>
                <Badge tone="accent">Succeeded</Badge>
              </span>
            </div>
            {exampleAttempts.map((a) => (
              <div
                key={a.attempt}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 12,
                  padding: "8px 0",
                  borderBottom: "1px solid var(--color-divider)",
                  opacity: a.opacity,
                }}
              >
                <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--color-text-muted)", width: 58, flex: "none" }}>
                  {a.time}
                </span>
                <span style={{ fontSize: 12, letterSpacing: "0.06em", textTransform: "uppercase", width: 62, flex: "none" }}>
                  Try {a.attempt}
                </span>
                <Badge tone={a.status === 200 ? "accent" : "neutral"}>{a.status}</Badge>
                <span style={{ fontSize: 12, color: "var(--color-text-muted)", marginLeft: "auto", whiteSpace: "nowrap" }}>
                  {a.note}
                </span>
              </div>
            ))}
          </div>
        </Card>
      </section>

      <footer
        style={{
          maxWidth: 1100,
          margin: "0 auto",
          padding: "24px 24px 48px",
          borderTop: "1px solid var(--color-divider)",
          fontSize: 13,
          color: "var(--color-text-muted)",
        }}
      >
        Gauntlet Relay v0.2.0 — Node/TypeScript and Go implementations, one schema, one REST contract.
      </footer>
    </div>
  );
}
